### ISSUE TITLE
PolicyTagManagerClient methods: 501 Operation is not implemented, or supported, or enabled

### ISSUE THREAD

**Issue by ricardolsmendes** [googleapis/python-datacatalog#33]
I'm writing a script to use the PolicyTagManagerClient, but all methods fail with a `google.api_core.exceptions.MethodNotImplemented: 501 Operation is not implemented, or supported, or enabled.` message.

- [x] Search the issues already opened: https://github.com/googleapis/python-datacatalog/issues
- [x] Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python
  - Related SO question: https://stackoverflow.com/questions/61916663/gcp-datacatalog-v1beta1-create-taxonomy-and-policy-tags-failed

#### Environment details

  - OS type and version: Windows 10
  - Python version: 3.7.2
  - pip version: 20.1.1
  - `google-cloud-datacatalog` version: 0.8.0

#### Steps to reproduce

  1. Run a script calling any of the PolicyTagManagerClient methods.

#### Code example

https://github.com/googleapis/python-datacatalog/pull/37/files

OR simply:

```python
def create_taxonomy(project_id):
    """Create a Taxonomy."""

    location = datacatalog_v1beta1.PolicyTagManagerClient.location_path(project_id, 'us')

    taxonomy = types.Taxonomy()
    taxonomy.display_name = "My Taxonomy"
    taxonomy.description = "This Taxonomy represents ..."

    datacatalog_v1beta1.PolicyTagManagerClient().create_taxonomy(
        parent=location, taxonomy=taxonomy)
```

#### Stack trace
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Operation is not implemented, or supported, or enabled."
        debug_error_string = "{"created":"@1590760876.084000000","description":"Error received from peer ipv4:216.58.192.42:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Operation is not implemented, or supported, or enabled.","grpc_status":12}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "policy_tags_manager.py", line 118, in <module>
    PolicyTagsManagerCLI.run(sys.argv[1:] if len(sys.argv) > 0 else sys.argv)
  File "policy_tags_manager.py", line 81, in run
    args.func(args)
  File "policy_tags_manager.py", line 110, in __create_taxonomy
    description=args.description)
  File "policy_tags_manager.py", line 34, in create_taxonomy
    return self.__datacatalog_facade.create_taxonomy(project_id, display_name, description)
  File "policy_tags_manager.py", line 63, in create_taxonomy
    parent=location, taxonomy=taxonomy)
  File "<REDACTED-PATH>\gcp-datacatalog-python\env\lib\site-packages\google\cloud\datacatalog_v1beta1\gapic\policy_tag_manager_client.py", line 305, in create_taxonomy
    request, retry=retry, timeout=timeout, metadata=metadata
  File "<REDACTED-PATH>\gcp-datacatalog-python\env\lib\site-packages\google\api_core\gapic_v1\method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "<REDACTED-PATH>\gcp-datacatalog-python\env\lib\site-packages\google\api_core\retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "<REDACTED-PATH>\gcp-datacatalog-python\env\lib\site-packages\google\api_core\retry.py", line 184, in retry_target
    return target()
  File "<REDACTED-PATH>\gcp-datacatalog-python\env\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "<REDACTED-PATH>\gcp-datacatalog-python\env\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.MethodNotImplemented: 501 Operation is not implemented, or supported, or enabled.
```

**Comment by ekohlwey-fb** [comment]
I'm having this issue as well. Does the Google team have an official view on whether or not this is a bug or misuse of the API?

**Comment by meredithslota** [comment]
Hi there — we are actively investigating this but do not yet have an answer. Google folks, this is being tracked at internal bug b/159220336.

**Comment by meredithslota** [comment]
Marking this as "external" since we're tracking most of the work internally and will report back when we have more progress. Thanks!

**Comment by tmshn** [comment]
I have a same issue for `list_tags` (using v2.0.0).
Note that this happens quite often, but not always. The API call succeeds something like once per ten times.

Here's the stacktrace:

```
Traceback (most recent call last):
  File "<REDACTED>/.venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "<REDACTED>/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "<REDACTED>/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Operation is not implemented, or supported, or enabled."
        debug_error_string = "{"created":"@1600948541.258238000","description":"Error received from peer ipv6:[2404:6800:4004:80a::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Operation is not implemented, or supported, or enabled.","grpc_status":12}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<REDACTED>/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "<REDACTED>/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "<REDACTED>/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<REDACTED>/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<REDACTED>/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "<REDACTED>/myapp/main.py", line 48, in export_metadata
    for table_metadata in fetcher.fetch_tables_metadata(project_id, dataset_id):
  File "<REDACTED>/myapp/gcp/fetch.py", line 55, in fetch_tables_metadata
    for tag in self.datacatalog.list_tags(request={"parent": path}):
  File "<REDACTED>/.venv/lib/python3.8/site-packages/google/cloud/datacatalog_v1beta1/services/data_catalog/client.py", line 2508, in list_tags
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "<REDACTED>/.venv/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "<REDACTED>/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "<REDACTED>/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "<REDACTED>/.venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.MethodNotImplemented: 501 Operation is not implemented, or supported, or enabled.
```

**Comment by yongyct** [comment]
Getting this issue for `create_entry_group`. 
Earlier docker images for my application a few days/past couple of weeks earlier that were working are now broken too.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Operation is not implemented, or supported, or enabled."
	debug_error_string = "{"created":"@1601032810.362696516","description":"Error received from peer ipv4:199.36.153.9:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Operation is not implemented, or supported, or enabled.","grpc_status":12}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/intient_research_admin_app_backend/csv_datacatalog_ingestion_fileset.py", line 139, in <module>
    create_fileset_method()
  File "/src/intient_research_admin_app_backend/csv_datacatalog_ingestion_fileset.py", line 88, in create_fileset_method
    entry_group=entry_group_obj)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/datacatalog_v1/gapic/data_catalog_client.py", line 503, in create_entry_group
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.MethodNotImplemented: 501 Operation is not implemented, or supported, or enabled.
```

**Comment by tameem92** [comment]
Seeing same issue for list_tags with images that were built a week ago. 

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Operation is not implemented, or supported, or enabled."
	debug_error_string = "{"created":"@1601040451.272763000","description":"Error received from peer ipv6:[2607:f8b0:400b:808::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Operation is not implemented, or supported, or enabled.","grpc_status":12}"
>
```

**Comment by joaopamaral** [comment]
I'm having this same issue for `list_tags` (google-cloud-datacatalog==1.0.0)! Yesterday was working with no problem and today I've noticed that after they change the Data Catalog UI, my code broked!

```
Error
Traceback (most recent call last):
  File "\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "\lib\site-packages\grpc\_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Operation is not implemented, or supported, or enabled."
	debug_error_string = "{"created":"@1601048577.314000000","description":"Error received from peer ipv6:[2800:3f0:4004:800::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Operation is not implemented, or supported, or enabled.","grpc_status":12}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
    map_tags = {t.template_display_name: t for t in data_catalog_client.list_tags(entry.name)}
  File "\lib\site-packages\google\api_core\page_iterator.py", line 212, in _items_iter
    for page in self._page_iter(increment=False):
  File "\lib\site-packages\google\api_core\page_iterator.py", line 243, in _page_iter
    page = self._next_page()
  File "\lib\site-packages\google\api_core\page_iterator.py", line 534, in _next_page
    response = self._method(self._request)
  File "\lib\site-packages\google\api_core\gapic_v1\method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "\lib\site-packages\google\api_core\retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "\lib\site-packages\google\api_core\retry.py", line 184, in retry_target
    return target()
  File "\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.MethodNotImplemented: 501 Operation is not implemented, or supported, or enabled.
```

**Comment by tmshn** [comment]
I don't see this problem happen today, so maybe this is the problem on the API side, not the library side?

**Comment by tameem92** [comment]
The problem has gone away for me as well. So I'm assuming it was on the API side.

**Comment by joaopamaral** [comment]
Same here. The library is working again!

**Comment by ricardolsmendes** [comment]
Thanks for the updates, folks

Important to let it clear the bug that caused `list_tags` to fail was [probably caused by an internal service disruption that might already be resolved](https://github.com/googleapis/java-datacatalog/issues/293#issuecomment-701009592), but it is not the same error originally reported here, despite the similar error messages.

**Comment by meredithslota** [comment]
The internal issue b/159220336 for the problem with the API was fixed, and the other issue was an internal service disruption. Closing this issue but please reopen a new issue if the problem re-occurs because it might be indicative of a new/different problem. Thanks!

**Comment by rvoitovich** [comment]
I had a similar problem. 
code:
```
from google.cloud.run_v2 import ListServicesRequest
from google.oauth2 import service_account
import google.cloud.run_v2 as run_v2

credentials = service_account.Credentials.from_service_account_file("key.json")

run_client = run_v2.ServicesClient(credentials=credentials)

request = ListServicesRequest(
    parent="projectId"
)

run_client.list_services(request=request)
```


error:
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Operation is not implemented, or supported, or enabled."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:216.58.215.106:443 {created_time:"2022-11-02T19:19:04.5426831+00:00", grpc_status:12, grpc_message:"Operation is not implemented, or supported, or enabled."}"
>
```

**Comment by meredithslota** [comment]
@rvoitovich Your issue seems to be in a different client library — https://cloud.google.com/python/docs/reference/run/latest/google.cloud.run_v2.types.ListServicesRequest seems to be the correct reference here. The relevant GitHub repo to report this issue on is here: https://github.com/googleapis/python-run Thanks!
